### PR TITLE
refactor: set agent worker and app worker console level

### PR DESCRIPTION
**Pull request by fengmk2**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
看来 nextTick 还不够长。。。

image

**Comment by popomore** [comment]
还是 setTimeout 吧，10ms 试试？这 ipc 发出去不知道啥机制。

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/1087

**Comment by fengmk2** [comment]
node 8 也一样 https://travis-ci.org/eggjs/egg-cluster/jobs/245424782#L749

**Pull request merged**
