### PR TITLE
fix: use --inspect-port after 8.x

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

vscode 1.21+ do not recognize `--debug-port`, so we need to switch to `--inspect-port`

- close https://github.com/eggjs/egg/issues/2325
- relate: https://github.com/Microsoft/vscode/issues/49865

### CODE REVIEW

**Comment by atian25** [comment]
1.16.1

**Comment by wenjiasen** [comment]
@atian25  请问已有的egg项目需要更新哪个包的依赖才能将egg-cluster升级到1.16.1？

**Comment by atian25** [comment]
删除依赖重新安装下看看，不要锁版本。

`rm -rf node-modules && npm i`

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by wenjiasen** [comment]
明白了，谢谢。@atian25

**Pull request merged**
