### PR TITLE
fix: should disable worker refork

### PR DESCRIPTION
**Pull request by fengmk2**
before it was killed.

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
依赖 https://github.com/node-modules/cfork/pull/110

**Comment by popomore** [comment]
这个用例能重现吗，close 后等待几秒 看看日志

**Comment by fengmk2** [comment]
之前的测试用例就是会输出 refork 的日志的。

**Comment by popomore** [comment]
那现在改了之后应该不会输出了？

**Comment by atian25** [comment]
1.12.2

**Pull request merged**
