### PR TITLE
feat: set window title under win32 platform

### PR DESCRIPTION
**Pull request by waitingsong**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
fell free to reopen if any other good idea.

**Comment by waitingsong** [comment]
用 process.title 设置windows窗口标题，然后用 ```tasklist /FI``` 以title/baseDir去匹配就可以解决window平台查找pid的问题了。

你这么急着关嘛呢……

**Comment by atian25** [comment]
我以为是独立一个 egg-scripts-win 去做了。
可以 reopen

**Comment by waitingsong** [comment]
npm stop with win32 support with this PR
https://github.com/eggjs/egg-scripts/pull/20

**Comment by waitingsong** [comment]
@atian25  
https://github.com/eggjs/egg-scripts/pull/20 这儿的测试写好了，需要这个 PR 才能测试 ```sto --title``` 功能

**Pull request closed without merging**
